#!/usr/bin/env bash
set -euo pipefail

# Install Deck's CLI shims and isolated Smithers workspace. The Prime
# conversation profile and its extension pack are converged by the root
# installer after this package is installed.
DECK_V2_HOME_DIR="${DECK_V2_HOME:-$HOME/.deck}"
REPO_V2="$(cd "$(dirname "$0")" && pwd)"
BIN_TARGET="${BIN_TARGET:-$HOME/.local/bin}"
DECK_REPO_ROOT="$(dirname "$REPO_V2")"

# CLI: a shim on PATH pointing at the repo bin, so both faces run one source.
mkdir -p "$BIN_TARGET"
ln -sfn "$REPO_V2/bin/deck-v2" "$BIN_TARGET/deck-v2"
printf 'installed deck-v2 CLI at %s/deck-v2\n' "$BIN_TARGET"

# deck: the worktree allocator CLI (repo cli/bin/deck). spawn shells out to it,
# so it must be on PATH wherever deck-v2 is.
DECK_SHIM="$BIN_TARGET/deck"
if [ -e "$DECK_SHIM" ] && [ ! -L "$DECK_SHIM" ]; then
  printf 'error: %s exists and is not a symlink; remove it by hand.\n' "$DECK_SHIM" >&2
  exit 1
fi
ln -sfn "$REPO_V2/../cli/bin/deck" "$DECK_SHIM"
printf 'installed deck CLI at %s\n' "$DECK_SHIM"


# smithers: a pinned PATH shim, never a global npm install. The version is read
# from src/smithers.ts — the one pin deck code shells out with — so shim and
# code cannot skew. bunx from a directory without a package.json can silently
# resolve a NEWER cached CLI, which is exactly what the pin prevents.
SMITHERS_VERSION="$(sed -n 's/^export const SMITHERS_VERSION = "\(.*\)";$/\1/p' "$REPO_V2/src/smithers.ts")"
if [ -z "$SMITHERS_VERSION" ]; then
  printf 'error: could not read SMITHERS_VERSION from %s/src/smithers.ts\n' "$REPO_V2" >&2
  exit 1
fi
SMITHERS_SHIM="$BIN_TARGET/smithers"
if [ -e "$SMITHERS_SHIM" ] && ! grep -q 'deck smithers shim' "$SMITHERS_SHIM" 2>/dev/null; then
  printf 'error: %s exists and is not the deck shim; remove it by hand.\n' "$SMITHERS_SHIM" >&2
  exit 1
fi
cat > "$SMITHERS_SHIM" <<EOF
#!/usr/bin/env bash
# deck smithers shim — pinned; generated by v2/install.sh from src/smithers.ts
exec bunx smithers-orchestrator@$SMITHERS_VERSION "\$@"
EOF
chmod +x "$SMITHERS_SHIM"
printf 'installed smithers shim (%s) at %s\n' "$SMITHERS_VERSION" "$SMITHERS_SHIM"

# Smithers runtime must be outside the development checkout. Copy only the
# workspace's static pack files; db, executions and logs are created here.
WORKFLOWS_SOURCE="${WORKFLOWS_SOURCE:-$(cd "$REPO_V2/../workflows" && pwd)}"
WORKSPACE_ROOT="$DECK_V2_HOME_DIR/state/smithers"
WORKSPACE_PACK="$WORKSPACE_ROOT/.smithers"
mkdir -p "$WORKSPACE_ROOT"
if [ -d "$WORKFLOWS_SOURCE/.smithers" ]; then
  mkdir -p "$WORKSPACE_PACK"
  # Copy the complete static pack. Preserve machine-local runtime directories
  # when an update refreshes the installed static files.
  for item in "$WORKFLOWS_SOURCE/.smithers"/* "$WORKFLOWS_SOURCE/.smithers"/.[!.]*; do
    [ -e "$item" ] || continue
    name="$(basename "$item")"
    case "$name" in node_modules|executions|runs|reports|sandboxes|logs|state|tmp|pg) continue ;; esac
    rm -rf "$WORKSPACE_PACK/$name"
    cp -a "$item" "$WORKSPACE_PACK/$name"
  done
  # Shared agents import the production Prime adapter, so the isolated runtime
  # receives its complete reviewed source/patch/provider dependency closure.
  mkdir -p \
    "$WORKSPACE_ROOT/pr-pipeline/lib/engines" \
    "$DECK_V2_HOME_DIR/state/ops" \
    "$DECK_V2_HOME_DIR/state/broker/prime" \
    "$DECK_V2_HOME_DIR/state/broker/node_modules" \
    "$DECK_V2_HOME_DIR/state/patches"
  cp -a "$WORKFLOWS_SOURCE/pr-pipeline/lib/models.ts" "$WORKSPACE_ROOT/pr-pipeline/lib/models.ts"
  cp -a "$WORKFLOWS_SOURCE/pr-pipeline/lib/model-policy.ts" "$WORKSPACE_ROOT/pr-pipeline/lib/model-policy.ts"
  cp -a "$WORKFLOWS_SOURCE/pr-pipeline/lib/engines/prime.ts" "$WORKSPACE_ROOT/pr-pipeline/lib/engines/prime.ts"
  cp -a "$WORKFLOWS_SOURCE/pr-pipeline/lib/engines/prime-model-policy.ts" "$WORKSPACE_ROOT/pr-pipeline/lib/engines/prime-model-policy.ts"
  cp -a "$DECK_REPO_ROOT/ops/prime-deck-profile.json" "$DECK_V2_HOME_DIR/state/ops/prime-deck-profile.json"
  cp -a "$DECK_REPO_ROOT/ops/prime-patches.sh" "$DECK_V2_HOME_DIR/state/ops/prime-patches.sh"
  cp -a "$DECK_REPO_ROOT/broker/prime/deck-provider.ts" "$DECK_V2_HOME_DIR/state/broker/prime/deck-provider.ts"
  rm -rf "$DECK_V2_HOME_DIR/state/patches/prime-agent"
  cp -a "$DECK_REPO_ROOT/patches/prime-agent" "$DECK_V2_HOME_DIR/state/patches/prime-agent"
  ln -sfn "$DECK_REPO_ROOT/broker/node_modules/zod" "$DECK_V2_HOME_DIR/state/broker/node_modules/zod"
fi
# Keep the old link name only for static compatibility. It is never the runtime
# workspace and no state is written through it.
WORKFLOWS_LINK="${WORKFLOWS_LINK:-$DECK_V2_HOME_DIR/workflows}"
if [ -L "$WORKFLOWS_LINK" ] || [ ! -e "$WORKFLOWS_LINK" ]; then
  mkdir -p "$(dirname "$WORKFLOWS_LINK")"
  ln -sfn "$WORKFLOWS_SOURCE" "$WORKFLOWS_LINK"
fi
if [ -f "$WORKSPACE_PACK/package.json" ] && [ ! -d "$WORKSPACE_PACK/node_modules" ]; then
  bun install --cwd "$WORKSPACE_PACK"
fi
