#!/usr/bin/env bash
set -euo pipefail

# Install the deck-v2 pi extension and the deck-v2 CLI.
# INSTALL_TARGET is overridable so tests never touch live ~/.pi.
#
# The extension is a DIRECTORY, not a flat symlink. pi discovers both
# `extensions/*.ts` and `extensions/*/index.ts`; a flat symlink resolves its
# relative sibling imports next to the SYMLINK rather than the real source, so
# the imports fail, and a flat sibling dropped beside it gets loaded as its own
# extension and rejected. The whole extension must live inside one directory
# where only index.ts is an entrypoint.
#
# deck-v2's extension imports ../*.ts from the v2 package, so the directory
# holds a symlink to the repo source tree instead of copies: one source of
# truth, and an edit is live without reinstalling.
# Default target is the ORCHESTRATOR HOME's own .pi, not the global ~/.pi/agent:
# these tools operate one home's fleet, so scoping them there keeps an unrelated
# pi session in another directory from loading a fleet-control extension.
# Override INSTALL_TARGET=$HOME/.pi/agent for a global install.
DECK_V2_HOME_DIR="${DECK_V2_HOME:-$HOME/.deck}"
INSTALL_TARGET="${INSTALL_TARGET:-$DECK_V2_HOME_DIR/.pi}"
REPO_V2="$(cd "$(dirname "$0")" && pwd)"
EXTENSIONS_DIR="$INSTALL_TARGET/extensions"
DEST="$EXTENSIONS_DIR/deck-v2"

mkdir -p "$EXTENSIONS_DIR"

# Refuse to clobber anything we cannot prove is ours.
if [ -e "$DEST" ] && [ ! -L "$DEST" ] && [ ! -d "$DEST" ]; then
  printf 'error: %s exists and is neither our directory nor a symlink.\n' "$DEST" >&2
  exit 1
fi

# A stale flat entry keeps failing even after a good directory exists beside it,
# because pi discovers extensions/*.ts too. Only remove one we can prove is ours.
stale="$EXTENSIONS_DIR/deck-v2.ts"
if [ -L "$stale" ]; then
  resolved="$(readlink "$stale")"
  case "$resolved" in
    "$REPO_V2"/*) rm -f "$stale"; printf 'removed stale flat entry %s\n' "$stale" ;;
    *) printf 'error: %s is a symlink we do not own.\n' "$stale" >&2; exit 1 ;;
  esac
elif [ -e "$stale" ]; then
  printf 'error: %s exists but is not our symlink; remove it by hand.\n' "$stale" >&2
  exit 1
fi

# pi resolves an extension's relative imports against the SYMLINK's directory,
# not the real file, so `index.ts -> .../src/extension/index.ts` cannot find
# `../events`. Verified: it fails with "Cannot find module '../events'".
#
# So the installed directory reproduces the source layout one level down:
#   deck-v2/extension/index.ts -> real src/extension/index.ts
#   deck-v2/<module>.ts        -> real src/<module>.ts
# `../events` from extension/index.ts then resolves to deck-v2/events.ts, which
# is the real module. Only extension/index.ts is nested, so pi finds exactly one
# entrypoint: pi discovers `*/index.ts`, not `*/*/index.ts`.
rm -rf "$DEST"
mkdir -p "$DEST/extension"
ln -sfn "$REPO_V2/src/extension/index.ts" "$DEST/extension/index.ts"
for module in "$REPO_V2"/src/*.ts; do
  name="$(basename "$module")"
  # index.ts is deliberately skipped: DEST/index.ts is the generated entrypoint
  # shim below, and symlinking it here would make the shim's redirect write
  # straight through the link into the repo's own src/index.ts.
  [ "$name" = "index.ts" ] && continue
  ln -sfn "$module" "$DEST/$name"
done
# The entrypoint pi loads. Re-exporting keeps the single-entrypoint rule while
# the real code stays in extension/index.ts next to its siblings.
rm -f "$DEST/index.ts"
printf 'export { default } from "./extension/index.ts";\n' > "$DEST/index.ts"

printf 'installed deck-v2 pi extension in %s\n' "$DEST"

# CLI: a shim on PATH pointing at the repo bin, so both faces run one source.
BIN_TARGET="${BIN_TARGET:-$HOME/.local/bin}"
mkdir -p "$BIN_TARGET"
ln -sfn "$REPO_V2/bin/deck-v2" "$BIN_TARGET/deck-v2"
printf 'installed deck-v2 CLI at %s/deck-v2\n' "$BIN_TARGET"

# smithers: a pinned PATH shim, never a global npm install. The version is read
# from src/smithers.ts — the one pin deck code shells out with — so shim and
# code cannot skew. bunx from a directory without a package.json can silently
# resolve a NEWER cached CLI, which is exactly what the pin prevents.
SMITHERS_VERSION="$(sed -n 's/^export const SMITHERS_VERSION = "\(.*\)";$/\1/p' "$REPO_V2/src/smithers.ts")"
if [ -z "$SMITHERS_VERSION" ]; then
  printf 'error: could not read SMITHERS_VERSION from %s/src/smithers.ts\n' "$REPO_V2" >&2
  exit 1
fi
SMITHERS_SHIM="$BIN_TARGET/smithers"
if [ -e "$SMITHERS_SHIM" ] && ! grep -q 'deck smithers shim' "$SMITHERS_SHIM" 2>/dev/null; then
  printf 'error: %s exists and is not the deck shim; remove it by hand.\n' "$SMITHERS_SHIM" >&2
  exit 1
fi
cat > "$SMITHERS_SHIM" <<EOF
#!/usr/bin/env bash
# deck smithers shim — pinned; generated by v2/install.sh from src/smithers.ts
exec bunx smithers-orchestrator@$SMITHERS_VERSION "\$@"
EOF
chmod +x "$SMITHERS_SHIM"
printf 'installed smithers shim (%s) at %s\n' "$SMITHERS_VERSION" "$SMITHERS_SHIM"

# Workflows: the fleet reads smithers runs from <home>/workflows/.smithers.
# The home is a plain directory, so the workspace arrives by symlink into the
# repo checkout (state stays gitignored there; the home itself gains no .git).
WORKFLOWS_LINK="${WORKFLOWS_LINK:-$DECK_V2_HOME_DIR/workflows}"
# Overridable so tests link a fixture instead of the real workspace (and never
# trigger the bun install below against the checkout).
WORKFLOWS_SOURCE="${WORKFLOWS_SOURCE:-$(cd "$REPO_V2/../workflows" && pwd)}"
if [ -L "$WORKFLOWS_LINK" ] || [ ! -e "$WORKFLOWS_LINK" ]; then
  mkdir -p "$(dirname "$WORKFLOWS_LINK")"
  ln -sfn "$WORKFLOWS_SOURCE" "$WORKFLOWS_LINK"
  printf 'linked %s -> %s\n' "$WORKFLOWS_LINK" "$WORKFLOWS_SOURCE"
else
  printf 'note: %s exists and is not a symlink; left alone.\n' "$WORKFLOWS_LINK"
fi

# `smithers ps` resolves through the workspace's own node_modules, so a fresh
# checkout needs one install before the fleet chip can read runs.
if [ -d "$WORKFLOWS_SOURCE/.smithers" ] && [ ! -d "$WORKFLOWS_SOURCE/.smithers/node_modules" ]; then
  bun install --cwd "$WORKFLOWS_SOURCE/.smithers"
fi
