#!/usr/bin/env bash
set -euo pipefail

# Install Deck's four standalone pi extensions and the deck-v2 CLI.
# INSTALL_TARGET is overridable so tests never touch live ~/.deck.
#
# Each extension is a DIRECTORY entrypoint. pi discovers both extensions/*.ts
# and extensions/*/index.ts; keeping one index.ts per surface prevents support
# libraries from being mistaken for extensions.
#
# The source entrypoints live at repo-root/extensions-pi/*.ts and import
# ../v2/src/*. When index.ts is symlinked into extensions/deck-*/index.ts, that
# same relative path resolves through extensions/v2/src/*. The shared symlink
# tree below deliberately preserves that layout.
DECK_V2_HOME_DIR="${DECK_V2_HOME:-$HOME/.deck}"
INSTALL_TARGET="${INSTALL_TARGET:-$DECK_V2_HOME_DIR/.pi}"
REPO_V2="$(cd "$(dirname "$0")" && pwd)"
BIN_TARGET="${BIN_TARGET:-$HOME/.local/bin}"
PI_ENTRY="$REPO_V2/node_modules/@earendil-works/pi-coding-agent/dist/cli.js"
PI_SHIM="$BIN_TARGET/pi"
is_deck_pi_shim() {
  local first second third extra escaped_entry expected_exec legacy_exec
  [ -f "$PI_SHIM" ] && [ ! -L "$PI_SHIM" ] || return 1
  if ! {
    IFS= read -r first &&
      IFS= read -r second &&
      IFS= read -r third &&
      ! IFS= read -r extra
  } < "$PI_SHIM"; then
    return 1
  fi
  printf -v escaped_entry '%q' "$PI_ENTRY"
  expected_exec="exec bun $escaped_entry \"\$@\""
  legacy_exec="exec bun \"$PI_ENTRY\" \"\$@\""
  [ "$first" = '#!/usr/bin/env bash' ] &&
    [ "$second" = '# deck pi shim — pinned; generated by v2/install.sh' ] &&
    { [ "$third" = "$expected_exec" ] || [ "$third" = "$legacy_exec" ]; }
}
if { [ -e "$PI_SHIM" ] || [ -L "$PI_SHIM" ]; } && ! is_deck_pi_shim; then
  printf 'error: %s already exists and is not the Deck pi shim; no changes were made.\n' "$PI_SHIM" >&2
  printf 'Keep it and install Deck commands in a separate directory:\n' >&2
  printf '  BIN_TARGET=%q bash %q\n' "$HOME/.local/deck-bin" "$REPO_V2/install.sh" >&2
  exit 1
fi
EXTENSION_SOURCE="$REPO_V2/../extensions-pi"
EXTENSIONS_DIR="$INSTALL_TARGET/extensions"
LIB_ROOT="$EXTENSIONS_DIR/v2"
LIB_DEST="$LIB_ROOT/src"
LIB_MARKER="$LIB_ROOT/.deck-v2-lib"
OLD_DEST="$EXTENSIONS_DIR/deck-v2"

mkdir -p "$EXTENSIONS_DIR"

TYPEBOX_SOURCE="$REPO_V2/node_modules/typebox"
TYPEBOX_TARGET="$EXTENSIONS_DIR/node_modules/typebox"
if [ ! -d "$TYPEBOX_SOURCE" ]; then
  printf 'error: extension dependencies are missing; run bun install --cwd %s\n' "$REPO_V2" >&2
  exit 1
fi
mkdir -p "$(dirname "$TYPEBOX_TARGET")"
if [ -e "$TYPEBOX_TARGET" ] || [ -L "$TYPEBOX_TARGET" ]; then
  if [ ! -L "$TYPEBOX_TARGET" ] || [ "$(readlink "$TYPEBOX_TARGET")" != "$TYPEBOX_SOURCE" ]; then
    printf 'error: %s exists but is not Deck'\''s typebox dependency.\n' "$TYPEBOX_TARGET" >&2
    exit 1
  fi
fi
ln -sfn "$TYPEBOX_SOURCE" "$TYPEBOX_TARGET"

# Retire only an installation whose entrypoint is provably the old Deck
# extension. Never silently delete a same-named user extension.
if [ -e "$OLD_DEST" ] || [ -L "$OLD_DEST" ]; then
  old_owned=false
  if [ -L "$OLD_DEST/extension/index.ts" ]; then
    case "$(readlink "$OLD_DEST/extension/index.ts")" in
      "$REPO_V2"/src/extension/index.ts) old_owned=true ;;
    esac
  elif [ -f "$OLD_DEST/index.ts" ] && grep -q 'export { default } from "./extension/index.ts";' "$OLD_DEST/index.ts"; then
    old_owned=true
  fi
  if [ "$old_owned" != true ]; then
    printf 'error: %s exists but is not the retired Deck extension.\n' "$OLD_DEST" >&2
    exit 1
  fi
  rm -rf "$OLD_DEST"
  printf 'removed retired deck-v2 orchestrator extension from %s\n' "$OLD_DEST"
fi

# A stale flat entry is still independently discovered by pi. Remove only one
# that resolves into this repository.
stale="$EXTENSIONS_DIR/deck-v2.ts"
if [ -L "$stale" ]; then
  resolved="$(readlink "$stale")"
  case "$resolved" in
    "$REPO_V2"/*) rm -f "$stale"; printf 'removed stale flat entry %s\n' "$stale" ;;
    *) printf 'error: %s is a symlink we do not own.\n' "$stale" >&2; exit 1 ;;
  esac
elif [ -e "$stale" ]; then
  printf 'error: %s exists but is not our symlink; remove it by hand.\n' "$stale" >&2
  exit 1
fi

# `v2` is a generic name in an extension directory. Claim it with an explicit
# source marker before writing any support-module symlink, and refuse collisions.
if [ -e "$LIB_ROOT" ] || [ -L "$LIB_ROOT" ]; then
  if [ -L "$LIB_ROOT" ] || [ ! -d "$LIB_ROOT" ]; then
    printf 'error: %s exists and is not Deck'\''s support directory.\n' "$LIB_ROOT" >&2
    exit 1
  fi
  owner=""
  if [ -f "$LIB_MARKER" ]; then IFS= read -r owner < "$LIB_MARKER" || true; fi
  if [ "$owner" != "$REPO_V2" ]; then
    printf 'error: %s exists without Deck'\''s matching ownership marker.\n' "$LIB_ROOT" >&2
    exit 1
  fi
else
  mkdir -p "$LIB_ROOT"
  printf '%s\n' "$REPO_V2" > "$LIB_MARKER"
fi
mkdir -p "$LIB_DEST"
for module in "$REPO_V2"/src/*.ts; do
  name="$(basename "$module")"
  # Nothing imports the v2 barrel, and leaving it out keeps the support tree
  # unambiguously non-loadable as a pi extension.
  [ "$name" = "index.ts" ] && continue
  ln -sfn "$module" "$LIB_DEST/$name"
done

for extension in deck-questions deck-ship deck-recall deck-usage; do
  source="$EXTENSION_SOURCE/$extension.ts"
  dest="$EXTENSIONS_DIR/$extension"
  flat="$EXTENSIONS_DIR/$extension.ts"
  if [ ! -f "$source" ]; then
    printf 'error: missing extension source %s\n' "$source" >&2
    exit 1
  fi
  if [ -e "$flat" ] || [ -L "$flat" ]; then
    printf 'error: stale flat extension entry %s must be removed by hand.\n' "$flat" >&2
    exit 1
  fi
  if [ -L "$dest" ] || { [ -e "$dest" ] && [ ! -d "$dest" ]; }; then
    printf 'error: %s exists and is not an extension directory.\n' "$dest" >&2
    exit 1
  fi
  mkdir -p "$dest"
  if [ -e "$dest/index.ts" ] || [ -L "$dest/index.ts" ]; then
    if [ ! -L "$dest/index.ts" ] || [ "$(readlink "$dest/index.ts")" != "$source" ]; then
      printf 'error: %s exists but is not Deck'\''s extension entrypoint.\n' "$dest/index.ts" >&2
      exit 1
    fi
  fi
  ln -sfn "$source" "$dest/index.ts"
  printf 'installed %s pi extension in %s\n' "$extension" "$dest"
done

# Plain Deck pi sessions share this pi agent directory. Install the subagent
# primitive there as its own independent extension.
INSTALL_TARGET="$INSTALL_TARGET" "$REPO_V2/../subagents/install.sh"

# CLI: a shim on PATH pointing at the repo bin, so both faces run one source.
mkdir -p "$BIN_TARGET"
ln -sfn "$REPO_V2/bin/deck-v2" "$BIN_TARGET/deck-v2"
printf 'installed deck-v2 CLI at %s/deck-v2\n' "$BIN_TARGET"

# deck: the worktree allocator CLI (repo cli/bin/deck). spawn shells out to it,
# so it must be on PATH wherever deck-v2 is.
DECK_SHIM="$BIN_TARGET/deck"
if [ -e "$DECK_SHIM" ] && [ ! -L "$DECK_SHIM" ]; then
  printf 'error: %s exists and is not a symlink; remove it by hand.\n' "$DECK_SHIM" >&2
  exit 1
fi
ln -sfn "$REPO_V2/../cli/bin/deck" "$DECK_SHIM"
printf 'installed deck CLI at %s\n' "$DECK_SHIM"

# pi: Deck pins the CLI dependency in v2/package.json. Use Bun for the generated
# wrapper so a clean install does not depend on a separately installed Node or
# global pi package.
if [ ! -f "$PI_ENTRY" ]; then
  printf 'error: pinned pi is missing; run bun install --cwd %s\n' "$REPO_V2" >&2
  exit 1
fi
printf '#!/usr/bin/env bash\n# deck pi shim — pinned; generated by v2/install.sh\nexec bun %q "$@"\n' \
  "$PI_ENTRY" > "$PI_SHIM"
chmod +x "$PI_SHIM"
printf 'installed pi shim at %s\n' "$PI_SHIM"

# smithers: a pinned PATH shim, never a global npm install. The version is read
# from src/smithers.ts — the one pin deck code shells out with — so shim and
# code cannot skew. bunx from a directory without a package.json can silently
# resolve a NEWER cached CLI, which is exactly what the pin prevents.
SMITHERS_VERSION="$(sed -n 's/^export const SMITHERS_VERSION = "\(.*\)";$/\1/p' "$REPO_V2/src/smithers.ts")"
if [ -z "$SMITHERS_VERSION" ]; then
  printf 'error: could not read SMITHERS_VERSION from %s/src/smithers.ts\n' "$REPO_V2" >&2
  exit 1
fi
SMITHERS_SHIM="$BIN_TARGET/smithers"
if [ -e "$SMITHERS_SHIM" ] && ! grep -q 'deck smithers shim' "$SMITHERS_SHIM" 2>/dev/null; then
  printf 'error: %s exists and is not the deck shim; remove it by hand.\n' "$SMITHERS_SHIM" >&2
  exit 1
fi
cat > "$SMITHERS_SHIM" <<EOF
#!/usr/bin/env bash
# deck smithers shim — pinned; generated by v2/install.sh from src/smithers.ts
exec bunx smithers-orchestrator@$SMITHERS_VERSION "\$@"
EOF
chmod +x "$SMITHERS_SHIM"
printf 'installed smithers shim (%s) at %s\n' "$SMITHERS_VERSION" "$SMITHERS_SHIM"

# Smithers runtime must be outside the development checkout. Copy only the
# workspace's static pack files; db, executions and logs are created here.
WORKFLOWS_SOURCE="${WORKFLOWS_SOURCE:-$(cd "$REPO_V2/../workflows" && pwd)}"
WORKSPACE_ROOT="$DECK_V2_HOME_DIR/state/smithers"
WORKSPACE_PACK="$WORKSPACE_ROOT/.smithers"
mkdir -p "$WORKSPACE_ROOT"
if [ -d "$WORKFLOWS_SOURCE/.smithers" ]; then
  mkdir -p "$WORKSPACE_PACK"
  # Copy the complete static pack. Preserve machine-local runtime directories
  # when an update refreshes the installed static files.
  for item in "$WORKFLOWS_SOURCE/.smithers"/* "$WORKFLOWS_SOURCE/.smithers"/.[!.]*; do
    [ -e "$item" ] || continue
    name="$(basename "$item")"
    case "$name" in node_modules|executions|runs|reports|sandboxes|logs|state|tmp|pg) continue ;; esac
    rm -rf "$WORKSPACE_PACK/$name"
    cp -a "$item" "$WORKSPACE_PACK/$name"
  done
  # agents.ts is part of the pack but its model catalog is owned by the pipeline.
  # Keep that relative import valid in the isolated runtime workspace.
  mkdir -p "$WORKSPACE_ROOT/pr-pipeline/lib"
  rm -f "$WORKSPACE_ROOT/pr-pipeline/lib/models.ts"
  cp -a "$WORKFLOWS_SOURCE/pr-pipeline/lib/models.ts" "$WORKSPACE_ROOT/pr-pipeline/lib/models.ts"
  # models.ts re-exports Deck's one canonical policy. Preserve that relative
  # import from state/smithers/pr-pipeline/lib into state/subagents/lib.
  mkdir -p "$DECK_V2_HOME_DIR/state/subagents/lib"
  rm -f "$DECK_V2_HOME_DIR/state/subagents/lib/model-policy.ts"
  cp -a "$REPO_V2/../subagents/lib/model-policy.ts" "$DECK_V2_HOME_DIR/state/subagents/lib/model-policy.ts"
fi
# Keep the old link name only for static compatibility. It is never the runtime
# workspace and no state is written through it.
WORKFLOWS_LINK="${WORKFLOWS_LINK:-$DECK_V2_HOME_DIR/workflows}"
if [ -L "$WORKFLOWS_LINK" ] || [ ! -e "$WORKFLOWS_LINK" ]; then
  mkdir -p "$(dirname "$WORKFLOWS_LINK")"
  ln -sfn "$WORKFLOWS_SOURCE" "$WORKFLOWS_LINK"
fi
if [ -f "$WORKSPACE_PACK/package.json" ] && [ ! -d "$WORKSPACE_PACK/node_modules" ]; then
  bun install --cwd "$WORKSPACE_PACK"
fi
