/**
 * Prompt templates, in code.
 *
 * The brief structure fm2 refined (worktree isolation assertion, status
 * protocol, definition of done) is generated by the spawn tool rather than
 * hand-scaffolded per task. fm2's own evidence for why templates belong in code:
 * a hand-written wait-for-another-lane clause cost 3.5 lane-days, and every lane
 * briefed from that text self-blocked identically. The scaffold is the contract.
 *
 * The captain's audit of a real fm2 brief removed four things, and none of them
 * appear here: the Herdr safety-gate section, every no-mistakes mention, the
 * project-memory boilerplate, and the delivery-mode taxonomy.
 *
 * Roles: ORCHESTRATOR (captain-facing, one per fleet) and WORKER (one per task).
 * Names are plain so a status line or prompt can never be ambiguous about which
 * is meant.
 */
import * as fs from "node:fs";
import * as path from "node:path";

/**
 * Projects whose convention is to sign agent-authored comments.
 *
 * Captain's decision: the signature is lindy's convention, not a global rule, so
 * it rides per-project rather than in every brief. The CONDUCT rule above it —
 * answer facts, never argue — is global, because that one is about behavior and
 * applies wherever an agent posts.
 */
const SIGNATURE_PROJECTS = new Set(["lindy"]);

export type WorkerBriefInput = {
	taskId: string;
	/** What to do. Front-loaded and self-contained: this is the whole contract. */
	task: string;
	/** Acceptance criteria. A worker is done when these pass, not when it feels done. */
	acceptance: string[];
	worktree: string;
	statusFile: string;
	kind: "ship" | "scout";
	project?: string;
	branch?: string;
	/** Scout only: where the report must land. */
	reportPath?: string;
	/** Extra task-specific context. Never lifecycle boilerplate. */
	context?: string;
};

/**
 * Worker bootstrap. Kept short on purpose: fm2's evidence is that 5.6-7K-char
 * front-loaded briefs needed 0-1 steers while iterative ones needed dozens, and
 * that prose rules decay. Long-form doctrine lives in skills, not here.
 */
export function workerBrief(input: WorkerBriefInput): string {
	const {
		taskId,
		task,
		acceptance,
		worktree,
		statusFile,
		kind,
		branch,
		reportPath,
		context,
		project,
	} = input;

	const sections: string[] = [];

	sections.push(`# Task: ${taskId}

${task}`);

	if (context !== undefined && context.trim().length > 0) {
		sections.push(`## Context\n\n${context.trim()}`);
	}

	sections.push(`## Acceptance

You are done when all of these are true, and not before:

${acceptance.map((item) => `- ${item}`).join("\n")}`);

	// Isolation assertion. Non-negotiable: a worker that writes to the primary
	// checkout corrupts the captain's own working copy.
	sections.push(`## Isolation

You are in a disposable worktree: ${worktree}

Verify before you write anything: run \`pwd -P\` and \`git rev-parse --show-toplevel\`.
Both must resolve inside that path. The path check is authoritative.
If it does not match, stop and append \`blocked: launched outside the task worktree\`
to your status file. Do not branch, commit, or edit.${
		branch === undefined ? "" : `\n\nFirst action: \`git checkout -b ${branch}\``
	}`);

	sections.push(`## Reporting

Report one event at a time with:

\`\`\`
deck-v2 note ${taskId} {verb} "{one short line}" --epoch "$DECK_RUN_EPOCH"
\`\`\`

Verbs: working, needs-decision, blocked, paused, resolved, done, failed.

Use that command, not a raw append to the file. It carries your run epoch, so if
this task was cancelled and restarted, your late report is refused instead of
being mistaken for the live run's. It also rejects a malformed line before it
reaches the orchestrator. If the command refuses your append, you have been
superseded: stop, and change nothing further.

Report sparingly. Append only when the orchestrator can act: a phase change it
would care about, or a terminal state. Progress narration belongs in your own
output, not the status file — a \`working:\` line that says nothing actionable is
noise that costs a supervision turn.

Use \`blocked:\` when you are stuck and need help. Use \`paused:\` only when you are
deliberately waiting on a known external event that will clear on its own.
If you hit the same obstacle twice, append \`blocked:\` and stop.

You never contact the captain. If a choice belongs to him (product direction,
irreversible action, scope change), append \`needs-decision: {the options}\` and
stop. The orchestrator asks him and returns the answer to you. Do not look for a
way to ask him yourself: one channel means one place to look, and two channels
lose decisions between them.`);

	sections.push(`## Scope

Do what the task says and stop. No adjacent fixes, no refactors, no cleanup you
were not asked for. A smaller diff is a better diff.

Never weigh "developer time" or estimate effort as a tradeoff. Correctness,
completeness and conciseness decide. Code is cheap; redoing it is not.

Before you hand-solve an operational flow — auth, deploy, CI, debugging
production — check this repo's committed skills and docs first. Most repos
document their own rails, and the rails are faster and correct.

Write as little code as the task allows. Prefer what already exists in this
repo, then the standard library, then a native platform feature, then an
already-installed dependency. Do not add a dependency for something a few lines
can do. Do not add an abstraction with one caller.

Tests: ask what assertion would actually catch this breaking, and write that.
Do not write one test per changed line. A test earns its place by going red on
the old behavior — if it passes against the code before your change, it is
testing nothing. Verify the mechanism fires rather than trusting a green run.`);

	if (kind === "scout") {
		sections.push(`## Definition of done

This is a scout task: the deliverable is the report, not a PR. Do not open one.

Write your findings to ${reportPath ?? "the report path in your task record"}.
The report must stand alone: what you did, what you found, the evidence
(commands run, output, file:line references), and what you recommend.

Your worktree is scratch and is discarded afterwards, so anything worth keeping
must be in the report. When it is complete, append \`done: {one-line conclusion}\`.`);
	} else {
		sections.push(`## Definition of done

Implement, commit on your branch, and open a PR.

Commit and PR titles use one of two forms:
  \`[TICKET-123]: short description\`
  \`type(area): short description\`   — type is fix, feat, chore, refactor, perf, ci, docs

Example: \`fix(evals): retry whole eval 5x on fallback + fallback visibility\`

The PR description is short: what broke, why it broke, what the fix does. For a
UI change, attach screenshots to the PR by uploading them — never commit image
files to the repo.

Code comments explain what a reader needs to understand the code. Never write a
comment that references a ticket as its reason: "FIXES ABC-123" in a comment is
noise, because the ticket is in the commit and the PR.

Never add a co-author or agent-attribution line to a commit.

Then append \`done: PR {url}\` and stop. You never merge; the captain gives that
word.

If you watch your own PR afterwards: review fixes are plain commits on this same
branch. Never open a second PR or a stacked child PR for rework on this task.

A PR that landed through a merge queue can read as closed and not merged.
Landing truth is the squash commit \`(#N)\` on the base branch, never the merged
flag.

In PR threads: agree, or answer with facts. Never argue with a reviewer — if you
believe a reviewer is wrong, append \`needs-decision:\` and stop. Write comments in
Simplified Technical English.${SIGNATURE_PROJECTS.has(project ?? "") ? `

Sign every comment you post \`-- tim's agent\`, because a reader deserves to know a
person did not write it.` : ""}

If review or CI comes back: a scoped correctness fix (a failing assertion, a
lint error, a rebase) is yours to make immediately. A product or architecture
question is not — append \`needs-decision:\` with the options and stop.`);
	}

	return sections.join("\n\n");
}

/**
 * The orchestrator contract is the FILE, v2/AGENTS.md — read, never generated.
 *
 * It used to also exist as a string constant here and the two had already
 * drifted. One owner: worker BRIEFS are generated because they splice per-task
 * values, but the contract has no variables, the captain edits it directly
 * through his home symlink, and a generator would silently overwrite those edits
 * on the next install. A file the human owns beats a string the code owns.
 */
export function orchestratorContract(): string {
	return fs.readFileSync(path.join(import.meta.dir, "..", "AGENTS.md"), "utf8");
}
